# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando repositorio
        uses: actions/checkout@v2
      - name: Use Node.js 12.18
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Instalando dependencias
        run: npm install    
      - name: Test
        run: npm test
        env:
          CI: true
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: salarios-app #Must be unique in Heroku
          heroku_email: estebegi@gmail.com


      
