# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando repositorio
        uses: actions/checkout@v2
      - name: Use Node.js 12.18
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Instalando dependencias
        run: npm install    
      - name: Test
        run: npm test
        env:
          CI: true
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: install heroku cli
        run: sudo snap install --classic heroku 
      - name: ingresar credenciales
        run: heroku login
      - name: correo
        run: estebegi@gmail.com
      - name: contraseña
        run: Estebanbedoya1
      - name: agregar repositorio
        run: heroku git:remote -a salarios-app
      - name: añadiendo archivos
        run: git add .
      - name: commit
        run: git commit -am "pofavo funciona"
      - name: push
        run: git push heroku master


      
