name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email estebegi@gmail.com
        git config --global user.name EstebanBedoya1
        git remote set-url origin https://${{ secret.PERSONAL_TOKEN }}@github.com/EstebanBedoya/Calculadora-salario.git
        npm build