# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando repositorio
        uses: actions/checkout@v2
      - name: Use Node.js 12.18.4
        uses: actions/setup-node@v1
        with:
          node-version: 12.8.4
      - name: Instalando dependencias
        run: npm install    
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Generando build
        run: npm build
      # Share artifact inside workflow
      - name: conpartiendo artefactos en el workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
