name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.18
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
      - name: Install dependencies
        run: npm install    
      - name: Test
        run: npm test
        env:
          CI: true
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email estebegi@gmail.com
        git config --global user.name EstebanBedoya1
        git remote set-url origin https://${{ secrets.PERSONAL_TOKEN }}@github.com/EstebanBedoya/Calculadora-salario.git
        npm run deploy
